theme = "base16_transparent"

[editor]
scrolloff = 10
mouse = false
shell = ["zsh", "-c"]
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
completion-replace = true
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.statusline]
left = ["mode", "version-control", "separator",  "spinner", "read-only-indicator"]
center = ["file-name", "spacer", "file-modification-indicator"]
right = ["diagnostics", "workspace-diagnostics", "file-type", "file-encoding", "position"]
separator = " LSP"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error", "info", "hint"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.whitespace]
render = "all"

[editor.whitespace.character]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "N"
newline = "⏎"
tabpad = "O"

[editor.indent-guides]
render = true
character = "┊"

[editor.soft-wrap]
enable = true
wrap-indicator = "⤷ "
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"
