# This file is for all of the configuration keys I could not find
[editor]
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
trim-final-newlines = true
trim-trailing-whitespace = true
rounded-corners = true
[editor.breadcrumb]
enable = true

[editor.auto-save.after-delay]
enable = true
timeout = 30000

[icons.vcs]
enable = true
branch = "⌬"

[icons.fs]
enable = true

[icons.kind]
enable = true
