"$schema" = 'https://starship.rs/config-schema.json'
continuation_prompt = '[⤷ ](bold 7)'
format = """\
$battery \
$hostname\
$directory\
$memory_usage\
$cmd_duration\
$fill\
$git_branch\
$git_status\
$git_metrics\
$git_state
$character"""

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰢝 "
discharging_symbol = "󰂍 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
format = '[$symbol$percentage]($style) '
[[battery.display]]
threshold = 20
style = "fg:bold fg:red"
[[battery.display]]
threshold = 50
style = "fg:bold fg:yellow"
[[battery.display]]
threshold = 100
style = "fg:bold fg:green"

[character]
success_symbol = "[I](bold green)"
error_symbol = "[I](bold red)"
vimcmd_symbol = "[❯](bold green)"

[directory]
truncation_length = 50
style = 'cyan bold'
read_only_style = "fg:bold fg:blink fg:bright-cyan"
repo_root_style = "fg:underline fg:bold fg:bright-cyan"
format = '[$path]($style)[$read_only]($read_only_style) '

[directory.substitutions]
".dotfiles" = " "
".config" = " "
"RustProjects" = " "
"Programming" = " "
"CProjects" = " "

[fill]
symbol = " "
style = "dimmed"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold red"

[git_status]
style = "bold 7"
format = '''([$all_status$ahead_behind]($style))'''
conflicted = '[!= $count ](bold red)'
ahead = '[⇡$count](bold green) '
behind = '[⇣$count](bold red) '
diverged = '[⇡$ahead_count](bold green) [⇣$behind_count](bold red) '
untracked = '[?$count ](bold 3)'
stashed = '[\$$count](7) '
modified = '[!$count](7) '
staged = '[+$count](bold green) '
renamed = '[»$count](7) '
deleted = '[✘$count](bold red) '

[git_metrics]
disabled = false

[git_state]
style = "bold purple"

[memory_usage]
threshold = 75
format = "[$ram( | $swap)]($style)"
style = "bold red"
disabled = false

[cmd_duration]
format = '[$duration]($style)'
show_notifications = true
min_time_to_notify = 50_000
style = 'bold 3'

[hostname]
trim_at = ''
format = '[$ssh_symbol$hostname]($style) '
aliases = { "Kydenpi" = "rpi" }
